version: "3.7"

services:
  pg:
    image: bitnami/postgresql
    container_name: alyabatch-pg
    environment:
      POSTGRES_USER: alyatest
      POSTGRES_PASSWORD: alyatest
      POSTGRES_DB: alyatest
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: alyabatch-redis
    ports:
      - "6379:6379"

  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    container_name: alyabatch-redis-cluster
    environment:
      IP: "0.0.0.0"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    command: server /data --console-address ":9001"
